Add uninstall, fix install database, use find_single_pkg just in case of duplicate package names

diff --git a/spackle b/spackle
--- a/spackle
+++ b/spackle
@@ -14,6 +14,7 @@ indexDir="$prefix/var/lib/spackle/index"
 packageDir="$prefix/var/cache/spackle/pkg"
 buildDir="$prefix/var/lib/spackle/build"
 #gpgDir="$prefix/etc/spackle.d/gnupg"
+tmpDir="$prefix/tmp"
 arch="auto"
 
 #Don't install these packages (ignore them when required as deps)
@@ -43,6 +44,14 @@ update_aur_index() {
     # Update from file list of the aur git mirror (approx 6 sec)
     echo "Updating ArchLinux AUR index" >&2
     curl "http://pkgbuild.com/git/aur-mirror.git/plain" | grep '^  <li>' | sed -e 's/<[^>]*>//g' -e 's/^\s*/aur\//' > "$indexDir/aur_index.txt"
+
+    # Download PKGBUILDS so we have dependency info
+    (   # use a subshell so we don't affect the current directory
+        cd $indexDir
+        wget http://aur3.org/all_pkgbuilds.tar.gz
+        # uncompress for faster dependency extraction
+        gunzip -c > all_pkgbuilds.tar
+    )
 }
 
 update_abs_index() {
@@ -86,6 +95,11 @@ find_pkg() {
     #curl -sS "$db_uri" | tar --exclude="*/*" -zt | grep -m 1 "^$1-[^-]*-[0-9]*/$" | sed 's@/$@@'
 }
 
+find_single_pkg() {
+    # return first result
+    find_pkg "$1" | sed '1 q'
+}
+
 get_aur3_info() {
     local name="$1"
 
@@ -98,7 +112,7 @@ get_deps_from_aur3() {
 }
 
 get_desc() {
-    local entry=$(find_pkg "$1")
+    local entry=$(find_single_pkg "$1")
     local repo=$(dirname $entry)
     local fullname=$(basename $entry)
     local name=${fullname%-*-*}
@@ -110,8 +124,41 @@ get_desc() {
     fi
 }
 
+get_pkgbuild() {
+    # print PKGBUILD to stdout
+    local entry=$(find_single_pkg "$1")
+    local repo=$(dirname $entry)
+    local fullname=$(basename $entry)
+    local name=${fullname%-*-*}
+    tar -Oxf "$indexDir/all_pkgbuilds.tar" "mirror/$name/PKGBUILD"
+}
+
 get_deps() {
-    get_deps_from_aur3 "$1"
+    # print depends list, one per line
+    local entry=$(find_single_pkg "$1")
+    [[ "${#entry}" == 0 ]] && echo "spackle: Error: package '$1' not found" >&2 && return 1
+    local repo=${entry%/*}
+    local fullname=${entry#*/}
+    local name=${fullname%-*-*}
+    if [[ "$repo" == "aur" ]]
+    then
+        (
+            #tar -Oxf "$indexDir/all_pkgbuilds.tar" "mirror/$name/PKGBUILD"
+            curl -sS https://aur.archlinux.org/packages/${name:0:2}/$name/PKGBUILD
+            cat <<END
+            IFS=\$'\n'
+            (( \${#depends[*]} > 0 )) && echo "\${depends[*]}"
+END
+        ) | rbash --norc --noprofile
+    else
+        tar -Oxf "$indexDir/$repo.db" "$fullname/depends" | \
+            sed -ne '/^%DEPENDS%/,/^$/{ //d;  p }' 
+    fi
+}
+
+# TODO: add version checking for dependencies. Use `vercmp` from pacman
+strip_version() {
+    sed -e 's/[<=>].*$//'
 }
 
 get_all_deps() {
@@ -130,10 +177,10 @@ get_all_deps() {
         pkg="${check[0]}"
         check=("${check[@]:1}")
         # remove empty string from $check
-        (( ${#check} == 0 )) && check=()
+        (( ${#check[0]} == 0 )) && check=()
 
         # get deps (filtered by ignore list)
-        newdeps="$(get_deps "$pkg" | grep -v -x -F "${ignore[*]}")"
+        newdeps="$(get_deps "$pkg" | strip_version | grep -v -x -F "${ignore[*]}")"
         if (( ${#newdeps} > 0 ))
         then
             check+=( $newdeps )
@@ -186,7 +233,7 @@ patch_pacman_c() {
 # BETA! doesn't fully work yet
 # Build makepkg from source
 bootstrap_makepkg_from_source() {
-    local entry=$(find_pkg pacman)
+    local entry=$(find_single_pkg pacman)
     local repo=$(dirname $entry)
     local fullname=$(basename $entry)
     local name=${fullname%-*-*}
@@ -207,7 +254,7 @@ bootstrap_makepkg_from_repo() {
     [[ -e "bootstrap" ]] || mkdir -p "bootstrap"
     cd "bootstrap"
     # get latest pacman version
-    local entry=$(find_pkg "pacman")
+    local entry=$(find_single_pkg "pacman")
     local repo=$(dirname $entry)
     local fullname=$(basename $entry)
     local name=${fullname%-*-*}
@@ -238,7 +285,46 @@ true
     cp "bin/makepkg" "$prefix/usr/bin/makepkg"
 }
 
+download_source() {
+    local entry="$1"
+    local repo=$(dirname "$entry")
+    local fullname=$(basename $entry)
+    local name=${fullname%-*-*}
+
+    echo "Downloading $entry" >&2
+    cd "$buildDir"
+    rm -rf "$name"
+
+    case "$repo" in
+        core|extra|community)
+            # TODO proper arch detection for "any"
+            rsync -q $rsync_flags "${abs[server]}::abs/$arch/$repo/$name" . ||
+                rsync -q $rsync_flags "${abs[server]}::abs/any/$repo/$name" . 
+            ;;
+        aur)
+            curl "http://aur.archlinux.org/packages/${name:0:2}/$name/$name.tar.gz" | tar -zx
+            ;;
+        *) echo "Unrecognized repo: '$repo'" >&2
+    esac
+
+    cd "$name"
+    # only modify PKGBUILD if we downloaded it
+    sed -i -e "s@/usr@$prefix/usr@g" PKGBUILD
+    sed -i -e "s@/etc@$prefix/etc@g" PKGBUILD
+    sed -i -e "s@/var@$prefix/var@g" PKGBUILD
+
+    if [[ "$name" == "pacman" ]]
+    then
+        patch_pacman_conf
+        patch_makepkg_conf
+        $MAKEPKG --nobuild --skipchecksums
+        (cd src/${fullname%-*}/src/pacman; patch_pacman_c)
+        makepkg_flags="$makepkg_flags --nodeps --skipchecksums --noextract"
+    fi
+}
+
 install_package() {
+    local no_download build_only dep_for found_source found_package
     local makepkg_flags="--nocheck"
     local rsync_flags='-mrtv --no-motd --delete-after --no-p --no-o --no-g'
     while [[ "${1:0:1}" == "-" ]]; do
@@ -247,18 +333,15 @@ install_package() {
         --no-download) local no_download=true ;;
         --dep-for=*)   local dep_for="${1#*=}" ;;
         # makepkg flags
-        -d|\
-        -dd|\
-        --nodeps|\
+        -d|-dd|--nodeps|\
         --nobuild|\
         --nocheck|\
         --noextract|\
-        -f|\
-        --force|\
+        -f|--force|\
         --skipchecksums|\
         --source)
                        makepkg_flags="$makepkg_flags $1" ;;
-        *)             echo "Skipping unrecognized option '$1'" ;;
+        *)             echo "Skipping unrecognized option '$1'" >&2 ;;
         esac
         shift
     done
@@ -267,63 +350,114 @@ install_package() {
 
     for arg in "$@" 
     do
-        cd "$buildDir"
-        local entry=$(find_pkg "$arg")
+        local entry=$(find_single_pkg "$arg")
         local repo=$(dirname "$entry")
         local fullname=$(basename $entry)
         local name=${fullname%-*-*}
 
-        echo ""
-        if [[ "$no_download" != true ]]
+        echo "" >&2
+        if [[ -e "$packageDir/$fullname-$arch.pkg.tar.xz" ]]
         then
-            echo "Downloading $entry"
-            rm -rf "$name"
-
-            case "$repo" in
-            core|extra|community)
-                # TODO proper arch detection for "any"
-                rsync -q $rsync_flags "${abs[server]}::abs/$arch/$repo/$name" . ||
-                    rsync -q $rsync_flags "${abs[server]}::abs/any/$repo/$name" . 
-                ;;
-            aur)
-                curl "http://aur.archlinux.org/packages/${name:0:2}/$name/$name.tar.gz" | tar -zx
-                ;;
-            *) echo "Unrecognized repo: '$repo'"
-            esac
-
-            cd "$name"
-            # only modify PKGBUILD if we downloaded it
-            sed -i -e "s@/usr@$prefix/usr@g" PKGBUILD
-            sed -i -e "s@/etc@$prefix/etc@g" PKGBUILD
-            sed -i -e "s@/var@$prefix/var@g" PKGBUILD
-
-            if [[ "$name" == "pacman" ]]
+            echo "Package found at '$packageDir/$fullname-$arch.pkg.tar.xz'" >&2
+        else
+            if [[ -e "$buildDir/$name" ]]
             then
-                patch_pacman_conf
-                patch_makepkg_conf
-                $MAKEPKG --nobuild --skipchecksums
-                (cd src/${fullname%-*}/src/pacman; patch_pacman_c)
-                makepkg_flags="$makepkg_flags --nodeps --skipchecksums --noextract"
+                echo "Build directory '$buildDir/$name' exists" >&2
+            elif [[ "$no_download" != true ]] 
+            then
+                download_source "$entry"
             fi
+
+            cd "$buildDir/$name"
+            echo "Building $entry" >&2
+            $MAKEPKG $makepkg_flags
         fi
 
-        cd "$buildDir/$name"
-        echo "Building $entry"
-        # restrict memory to prevent Dreamhost from killing the process
-        #ulimit -v 499000  
-        $MAKEPKG $makepkg_flags
-
         [[ "$build_only" == "true" ]] && continue
+
         [[ -e "$dbDir" ]] || mkdir -p "$dbDir"
 
-        for package_file in $(find . "$packageDir" -name "$name*.pkg.tar.xz")
+        for package_file in $(find "$packageDir" -name "$fullname*.pkg.tar.xz")
         do
-            echo "Installing $(basename $package_file)"
-            tar -C "$prefix" --strip-components=3 --show-transformed-names --index-file="$name.files" -xf "$package_file"
-            mv "$name.files" "$dbDir"
-            [[ ! -z "$dep_for" ]] && echo "$dep_for" >> "$dbDir/$name.dep-for"
+            echo "Installing $(basename $package_file)" >&2
+            tar -C "$prefix" --strip-components=3 --show-transformed-names --index-file="$name.files" -xvf "$package_file"
+            mkdir -p "$dbDir/$name"
+            mv "$name.files" "$dbDir/$name/files"
+            tar -Oxf "$package_file" ".PKGINFO" | parse_pkginfo > "$dbDir/$name/desc"
+            [[ -n "$dep_for" ]] && echo "$dep_for" >> "$dbDir/$name/dep-for"
         done
     done
+
+    hash -r
+}
+
+# Converts the .PKGINFO in a *.pkg.tar.xz into a desc file
+# Usage
+# cat .PKGINFO | parse_pkginfo > desc
+parse_pkginfo() {
+    local key value prev_key add_install_date 
+    prev_key=""
+    while read line
+    do
+        [[ "${line:0:1}" == "#" ]] && continue
+        # Split on " = "
+        key="${line%% = *}"
+        value="${line#* = }"
+        if [[ "$key" != "$prev_key" ]]
+        then
+            [[ -n "$prev_key" ]] && echo ""
+            # Insert install date after the build date
+            # Note: we can convert the posix time to a normal time
+            # string with $(date -d "@1339629663")
+            if [[ "$prev_key" == "builddate" ]]
+            then
+                add_install_date=true
+                echo "%INSTALLDATE%"
+                date '+%s'
+                echo ""
+            fi
+            # Convert key name to upper case
+            echo "%${key^^}%"
+            prev_key="$key"
+        fi
+        echo "$value"
+    done
+    if [[ -z "$add_install_date" ]]
+    then
+        echo ""
+        echo "%INSTALLDATE%"
+        date '+%s'
+    fi
+}
+
+uninstall_package() {
+    local name file dir dir_list
+    name="$1"
+    [[ ! -e "$dbDir/$name" ]] && echo "Package '$name' not installed" >&2 && return 1
+    [[ ! -e "$dbDir/$name/files" ]] && echo "Package '$name' missing files list" >&2
+
+    # Delete files first
+    while read file
+    do
+        if [[ -d "$prefix/$file" ]]
+        then
+            dir_list="$file $dir_list"
+        else
+            rm "$prefix/$file" 2>/dev/null && echo "deleted '$prefix/$file'" >&2
+        fi
+    done < "$dbDir/$name/files"
+
+    # Delete empty directories
+    for dir in $dir_list
+    do
+        echo "$dir"
+        rmdir "$prefix/$dir" 2>/dev/null && echo "deleted '$prefix/$dir'" >&2
+    done
+
+    rm -rf "$dbDir/$name"
+    echo "Uninstalled '$name'" >&2
+
+    hash -r
 }
 
 get_name_ver_rel() {
@@ -364,6 +498,7 @@ usage() {
     echo "    install --force         pass '-f' to makepkg"
     echo "    search      find package_name in search index (Perl regex supported)"
     echo "    show        print package info"
+    echo "    uninstall   remove an installed package"
     echo "    update      updates the package indices"
     echo ""
     echo ""
@@ -406,10 +541,13 @@ case "$1" in
     update)             update_index ;;
     build)              shift; build_package "$@" ;;
     install)            shift; install_package "$@" ;;
+    uninstall)          shift; uninstall_package "$@" ;;
     info|show)          shift; get_desc "$1" ;;
     deps)               shift; get_deps "$1" ;;
     alldeps)            shift; get_all_deps "$1" ;;
+    desc)               shift; get_desc "$1" ;;
+    pkgbuild)           shift; get_pkgbuild "$1" ;;
     aur3)               shift; get_aur3_info "$1" ;;
-    *)                  echo "Unrecognized command: '$1'"
+    *)                  echo "Unrecognized command: '$1'" >&2
 esac
 
